- name: Create Jenkins Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/job.xml') }}"
    name: "{{ item.name }}"
    password: admin
    url: http://jenkins-internal.azdevopsb82.online:8080
    user: admin
  loop: "{{ jobs }}"


