- name: Seed Jobs
  hosts: localhost
  connection: local
  roles:
    - jobs
  vars:
    folders:
      - { name: CI }
    jobs:
      #- { name: sample, repo_name: learn-jenkins }
      - { name: cart, repo_name: roboshop-cart, folder: CI }
